import os
import re
from typing import Optional

def find_share_a_cart_extension() -> Optional[str]:
    """
    Search for Share-A-Cart extension files (.crx or unpacked extension directories)
    in the finance/extensions directory or known paths.
    """
    pkg_dir = os.path.dirname(os.path.abspath(__file__))
    candidate_dirs = [
        os.path.join(os.path.dirname(pkg_dir), "extensions"),
        os.path.join(pkg_dir, "extensions"),
    ]
    for ext_dir in candidate_dirs:
        if os.path.exists(ext_dir):
            for item in os.listdir(ext_dir):
                full_path = os.path.join(ext_dir, item)
                # Check for .crx file
                if item.endswith(".crx"):
                    return full_path
                # Check for unpacked extension directory
                if os.path.isdir(full_path) and os.path.exists(os.path.join(full_path, "manifest.json")):
                    return full_path
    return None

def normalize_share_a_cart_url(raw_input: str) -> Optional[str]:
    """
    Normalize user input or cart code into a full Share-A-Cart URL.
    Examples:
      - 'https://shareacart.net/get/ABC1234' -> 'https://shareacart.net/get/ABC1234'
      - 'ABC1234' -> 'https://shareacart.net/get/ABC1234'
      - 'shareacart.net/get/ABC1234' -> 'https://shareacart.net/get/ABC1234'
    """
    if not raw_input or not raw_input.strip():
        return None
    cleaned = raw_input.strip()
    if cleaned.startswith("http://") or cleaned.startswith("https://"):
        return cleaned
    # Match standalone cart code or relative path
    code_match = re.search(r'(?:shareacart\.net/(?:get|cart)/)?([A-Za-z0-9_-]{5,20})', cleaned)
    if code_match:
        return f"https://shareacart.net/get/{code_match.group(1)}"
    return f"https://shareacart.net/get/{cleaned}"

def create_share_a_cart_link(items: list[dict], vendor_name: str = "amazon", order_title: str = "MRG Order") -> Optional[str]:
    """
    Automatically creates a Share-A-Cart link via the official Share-A-Cart API.
    items: list of dicts with keys 'item_name'/'title', 'link'/'url', 'quantity'/'qty', 'cost'/'price'.
    """
    import requests
    cart_entries = []
    for it in items:
        url = it.get("link") or it.get("url") or ""
        qty = int(it.get("quantity") or it.get("qty") or 1)
        name = it.get("item_name") or it.get("title") or "Item"
        price = str(it.get("cost") or it.get("price") or "")
        
        # Extract ASIN for Amazon
        asin = it.get("asin")
        if not asin and url:
            try:
                from price_scraper import extract_amazon_asin
                asin = extract_amazon_asin(url)
            except Exception:
                asin_m = re.search(r"/(?:dp|gp/product|gp/aw/d|product|d)/([A-Z0-9]{10})", url, re.IGNORECASE)
                if asin_m:
                    asin = asin_m.group(1).upper()
            
        cart_entries.append({
            "asin": asin,
            "name": name,
            "title": name,
            "url": it.get("resolved_url") or url,
            "originalUrl": url,
            "quantity": qty,
            "price": price
        })
        
    vendor_key = "amazon" if "amazon" in vendor_name.lower() else vendor_name.lower()
    payload = {
        "cartid": None,
        "cart": cart_entries,
        "vendor": vendor_key,
        "title": order_title or "MRG Purchase Request",
        "note": "Generated by MRG Finance Automation",
        "ccy": "USD"
    }
    
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Origin": "https://share-a-cart.com",
        "Referer": "https://share-a-cart.com/make"
    }
    
    try:
        resp = requests.post("https://share-a-cart.com/api/make/saveWithMetadata", json=payload, headers=headers, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            cid = data.get("cartid")
            if cid:
                return f"https://share-a-cart.com/get/{cid}"
    except Exception as e:
        print(f"  ⚠️ Automatic Share-A-Cart generation notice: {e}")
    return None

def prompt_for_share_a_cart(item_count: int, vendor_name: str = "Vendor", auto_url: Optional[str] = None) -> Optional[str]:
    """
    Interactive prompt presenting the automatically generated Share-A-Cart link,
    or letting the user paste/override it.
    """
    print("\n" + "━" * 68)
    print(f"🛒  Share-A-Cart Link ({item_count} item(s) for {vendor_name})")
    print("━" * 68)
    if auto_url:
        print(f"  ✨ Automatically Created Cart Link: {auto_url}")
        print("  Press Enter to use this link, or paste a replacement below:")
    else:
        print("  1. In your open browser window, open your shopping cart.")
        print("  2. Click the 'Share-A-Cart' extension icon and click 'Create Cart'.")
        print("  3. Paste the Share-A-Cart link or code below (or press Enter to skip):")
    
    try:
        user_input = input("👉 Share-A-Cart Link/Code: ").strip()
        if not user_input and auto_url:
            print(f"  ✅ Using Share-A-Cart link: {auto_url}")
            return auto_url
        url = normalize_share_a_cart_url(user_input)
        if url:
            print(f"  ✅ Registered Share-A-Cart link: {url}")
            return url
        else:
            print("  ⏩ Skipped Share-A-Cart link (none provided).")
            return None
    except (KeyboardInterrupt, EOFError):
        print("\n  ⏩ Skipped Share-A-Cart link.")
        return auto_url

